# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-24 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def load_status_types(apps, schema_editor):
    Status_Types = apps.get_model("statustypes", "StatusTypes")
    yesterday_status = Status_Types(id=0,type='Yesterday')
    yesterday_status.save()
    today_status = Status_Types(id=0,type='Today')
    today_status.save()
    issue_status = Status_Types(id=0,type='Issue')
    issue_status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_JiraIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_issue_id', models.TextField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Status')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='status_jiraissue',
            name='status_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StatusTypes'),
        ),
        migrations.RunPython(load_status_types),
    ]
