# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160624_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_jiraissue',
            name='status_particulars_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status_jiraissue',
            name='status_type',
            field=models.TextField(),
        ),
    ]
