# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-28 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160627_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_jiraissue',
            name='jira_issue_text',
            field=models.TextField(default=None),
        ),
    ]
