# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_status_jiraissue_jira_issue_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_jiraissue',
            name='jira_issue_id',
            field=models.TextField(default=None),
        ),
    ]
