# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-28 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160628_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_jiraissue',
            name='jira_issue_text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='status_jiraissue',
            name='status_particulars_id',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='status_jiraissue',
            name='status_type',
            field=models.TextField(default='Yesterday'),
        ),
    ]
